//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServisCagir4.ServiceReference1 {
    using System;
    using System.Data;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bagla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Bagla(int ekipNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bagla", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BaglaAsync(int ekipNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiKaydet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int KisiKaydet(string ad, string soyad, int ekipNo, int bolgeNo, string resim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiKaydet", ReplyAction="*")]
        System.Threading.Tasks.Task<int> KisiKaydetAsync(string ad, string soyad, int ekipNo, int bolgeNo, string resim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int KisiSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiSil", ReplyAction="*")]
        System.Threading.Tasks.Task<int> KisiSilAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Guncelle(int id, string ad, string soyad, int ekipNo, int bolgeNo, string resim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GuncelleAsync(int id, string ad, string soyad, int ekipNo, int bolgeNo, string resim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listele", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listele();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listele", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListeleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : webServisCagir4.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<webServisCagir4.ServiceReference1.WebService1Soap>, webServisCagir4.ServiceReference1.WebService1Soap {
        internal EventHandler<BaglaCompletedEventArgs> BaglaCompleted { get; set; }

        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Bagla(int ekipNum) {
            return base.Channel.Bagla(ekipNum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BaglaAsync(int ekipNum) {
            return base.Channel.BaglaAsync(ekipNum);
        }
        
        public int KisiKaydet(string ad, string soyad, int ekipNo, int bolgeNo, string resim) {
            return base.Channel.KisiKaydet(ad, soyad, ekipNo, bolgeNo, resim);
        }
        
        public System.Threading.Tasks.Task<int> KisiKaydetAsync(string ad, string soyad, int ekipNo, int bolgeNo, string resim) {
            return base.Channel.KisiKaydetAsync(ad, soyad, ekipNo, bolgeNo, resim);
        }
        
        public int KisiSil(int id) {
            return base.Channel.KisiSil(id);
        }
        
        public System.Threading.Tasks.Task<int> KisiSilAsync(int id) {
            return base.Channel.KisiSilAsync(id);
        }
        
        public int Guncelle(int id, string ad, string soyad, int ekipNo, int bolgeNo, string resim) {
            return base.Channel.Guncelle(id, ad, soyad, ekipNo, bolgeNo, resim);
        }
        
        public System.Threading.Tasks.Task<int> GuncelleAsync(int id, string ad, string soyad, int ekipNo, int bolgeNo, string resim) {
            return base.Channel.GuncelleAsync(id, ad, soyad, ekipNo, bolgeNo, resim);
        }
        
        public System.Data.DataTable Listele() {
            return base.Channel.Listele();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListeleAsync() {
            return base.Channel.ListeleAsync();
        }

        internal void BaglaAsync()
        {
            throw new NotImplementedException();
        }
    }
}
